# Generated by Django 5.0.6 on 2024-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
