# Generated by Django 5.0.6 on 2024-06-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather',
            new_name='climate',
        ),
    ]
