# Generated by Django 5.0.6 on 2024-06-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_weather_climate'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
