# Generated by Django 5.0.6 on 2024-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_climate_wind_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climate',
            old_name='humidity',
            new_name='flood',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='icon',
        ),
        migrations.AddField(
            model_name='climate',
            name='carbon_emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='climate',
            name='rainfall',
            field=models.FloatField(default=0),
        ),
    ]
